[2021-11-29 22:19:21,751] {taskinstance.py:1035} INFO - Dependencies all met for <TaskInstance: test.print_date scheduled__2021-11-28T22:19:19.840751+00:00 [queued]>
[2021-11-29 22:19:21,775] {taskinstance.py:1035} INFO - Dependencies all met for <TaskInstance: test.print_date scheduled__2021-11-28T22:19:19.840751+00:00 [queued]>
[2021-11-29 22:19:21,775] {taskinstance.py:1241} INFO - 
--------------------------------------------------------------------------------
[2021-11-29 22:19:21,775] {taskinstance.py:1242} INFO - Starting attempt 1 of 2
[2021-11-29 22:19:21,775] {taskinstance.py:1243} INFO - 
--------------------------------------------------------------------------------
[2021-11-29 22:19:21,822] {taskinstance.py:1262} INFO - Executing <Task(BashOperator): print_date> on 2021-11-28 22:19:19.840751+00:00
[2021-11-29 22:19:21,841] {standard_task_runner.py:52} INFO - Started process 340 to run task
[2021-11-29 22:19:21,855] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'test', 'print_date', 'scheduled__2021-11-28T22:19:19.840751+00:00', '--job-id', '4', '--raw', '--subdir', 'DAGS_FOLDER/test.py', '--cfg-path', '/tmp/tmpqc7xhq5m', '--error-file', '/tmp/tmp36qxxsqf']
[2021-11-29 22:19:21,857] {standard_task_runner.py:77} INFO - Job 4: Subtask print_date
[2021-11-29 22:19:21,934] {logging_mixin.py:109} INFO - Running <TaskInstance: test.print_date scheduled__2021-11-28T22:19:19.840751+00:00 [running]> on host 2676bc454327
[2021-11-29 22:19:22,062] {taskinstance.py:1429} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=***@example.com
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=test
AIRFLOW_CTX_TASK_ID=print_date
AIRFLOW_CTX_EXECUTION_DATE=2021-11-28T22:19:19.840751+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-11-28T22:19:19.840751+00:00
[2021-11-29 22:19:22,064] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2021-11-29 22:19:22,065] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'date']
[2021-11-29 22:19:22,090] {subprocess.py:85} INFO - Output:
[2021-11-29 22:19:22,109] {subprocess.py:89} INFO - Mon Nov 29 22:19:22 UTC 2021
[2021-11-29 22:19:22,110] {subprocess.py:93} INFO - Command exited with return code 0
[2021-11-29 22:19:22,170] {taskinstance.py:1280} INFO - Marking task as SUCCESS. dag_id=test, task_id=print_date, execution_date=20211128T221919, start_date=20211129T221921, end_date=20211129T221922
[2021-11-29 22:19:22,262] {local_task_job.py:154} INFO - Task exited with return code 0
[2021-11-29 22:19:22,334] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
