[2021-11-29 22:24:45,382] {taskinstance.py:1035} INFO - Dependencies all met for <TaskInstance: test.algorithm manual__2021-11-29T22:24:44.943816+00:00 [queued]>
[2021-11-29 22:24:45,415] {taskinstance.py:1035} INFO - Dependencies all met for <TaskInstance: test.algorithm manual__2021-11-29T22:24:44.943816+00:00 [queued]>
[2021-11-29 22:24:45,416] {taskinstance.py:1241} INFO - 
--------------------------------------------------------------------------------
[2021-11-29 22:24:45,416] {taskinstance.py:1242} INFO - Starting attempt 1 of 2
[2021-11-29 22:24:45,417] {taskinstance.py:1243} INFO - 
--------------------------------------------------------------------------------
[2021-11-29 22:24:45,451] {taskinstance.py:1262} INFO - Executing <Task(HelloOperator): algorithm> on 2021-11-29 22:24:44.943816+00:00
[2021-11-29 22:24:45,458] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'test', 'algorithm', 'manual__2021-11-29T22:24:44.943816+00:00', '--job-id', '5', '--raw', '--subdir', 'DAGS_FOLDER/test.py', '--cfg-path', '/tmp/tmpf82wjr0_', '--error-file', '/tmp/tmpn4yqe14b']
[2021-11-29 22:24:45,458] {standard_task_runner.py:77} INFO - Job 5: Subtask algorithm
[2021-11-29 22:24:45,455] {standard_task_runner.py:52} INFO - Started process 574 to run task
[2021-11-29 22:24:45,532] {logging_mixin.py:109} INFO - Running <TaskInstance: test.algorithm manual__2021-11-29T22:24:44.943816+00:00 [running]> on host 2676bc454327
[2021-11-29 22:24:45,655] {taskinstance.py:1429} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=***@example.com
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=test
AIRFLOW_CTX_TASK_ID=algorithm
AIRFLOW_CTX_EXECUTION_DATE=2021-11-29T22:24:44.943816+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2021-11-29T22:24:44.943816+00:00
[2021-11-29 22:24:45,655] {logging_mixin.py:109} INFO - Hello bruno
[2021-11-29 22:24:45,701] {taskinstance.py:1280} INFO - Marking task as SUCCESS. dag_id=test, task_id=algorithm, execution_date=20211129T222444, start_date=20211129T222445, end_date=20211129T222445
[2021-11-29 22:24:45,761] {local_task_job.py:154} INFO - Task exited with return code 0
[2021-11-29 22:24:45,814] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
